import type { PowEvent } from "./types";

const GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token";
const GOOGLE_CALENDAR_BASE = "https://www.googleapis.com/calendar/v3";

function requiredEnv(name: string): string {
  const v = process.env[name];
  if (!v) throw new Error(`${name} is not set`);
  return v;
}

async function getGoogleAccessToken(): Promise<string> {
  const clientId = requiredEnv("GOOGLE_CLIENT_ID");
  const clientSecret = requiredEnv("GOOGLE_CLIENT_SECRET");
  const refreshToken = requiredEnv("GOOGLE_REFRESH_TOKEN");

  const res = await fetch(GOOGLE_TOKEN_URL, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      client_id: clientId,
      client_secret: clientSecret,
      refresh_token: refreshToken,
      grant_type: "refresh_token",
    }),
    cache: "no-store",
  });

  if (!res.ok) {
    const txt = await res.text().catch(() => "");
    throw new Error(`Google token refresh failed: ${res.status} ${txt}`);
  }

  const json = (await res.json()) as { access_token: string };
  return json.access_token;
}

function calendarId(): string {
  // Use "primary" or a specific calendar id (recommended: a dedicated Pow calendar).
  return requiredEnv("GOOGLE_CALENDAR_ID");
}

function buildCalendarEventInput(e: PowEvent) {
  const when = new Date(e.occurredAt);
  const end = new Date(when.getTime() + 60 * 1000);

  const typeLabel =
    e.type === "commit"
      ? "Commit"
      : e.type === "pull_request_opened"
        ? "PR opened"
        : e.type === "pull_request_merged"
          ? "PR merged"
          : e.type === "pull_request_closed"
            ? "PR closed"
            : e.type === "workflow_run"
              ? "CI run"
              : e.type === "release"
                ? "Release"
                : "Event";

  // No commit messages; only type + repo + link.
  const summary = `PoW: ${typeLabel} — ${e.repo}`;
  const description = `Repo: ${e.repo}\nType: ${e.type}\nLink: ${e.url}\n\n(Generated by portfolio Proof of Work)`;

  return {
    summary,
    description,
    start: { dateTime: when.toISOString() },
    end: { dateTime: end.toISOString() },
    // De-dupe via iCalUID, stable across retries.
    iCalUID: `${e.dedupeKey}@pow.shobhitsrivastava.com`,
    source: { title: "Proof of Work", url: e.url },
  };
}

export async function writePowEventsToGoogleCalendar(events: PowEvent[]): Promise<void> {
  if (events.length === 0) return;

  const token = await getGoogleAccessToken();
  const calId = encodeURIComponent(calendarId());

  // Insert each as its own Calendar event (noisy but granular).
  for (const e of events) {
    const body = buildCalendarEventInput(e);
    const res = await fetch(`${GOOGLE_CALENDAR_BASE}/calendars/${calId}/events`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(body),
      cache: "no-store",
    });

    // If duplicate, ignore (Google will reject duplicate iCalUID in some cases).
    if (res.ok) continue;
    const txt = await res.text().catch(() => "");
    // 409 is typical for already-existing iCalUID; treat as success.
    if (res.status === 409) continue;
    // If calendar isn't configured, fail loudly (so you notice in logs).
    throw new Error(`Calendar insert failed: ${res.status} ${txt}`);
  }
}

